### ISSUE TITLE
Update to use latest version of flashier

### ISSUE THREAD

**Issue by pcarbo** [jean997/sumstatFactors#1]
@willwerscheid would you be able to help Jean update `sumstatFactors` to work with the revamped `flashier` interface? Nathan has been using `sumstatFactors` and made me aware that the new version of `flashier` has broken Jean's package.

**Comment by willwerscheid** [comment]
Yes of course. Could you please point me to the code that uses flash functions/objects?

**Comment by pcarbo** [comment]
@willwerscheid Probably you want to start with `gfa_fit` [here](https://github.com/jean997/sumstatFactors/blob/master/R/gfa_fit.R).

**Comment by jean997** [comment]
Ooh thanks. I didn't know there was a new version of flashier. I will see if I can get to this this week.

**Comment by willwerscheid** [comment]
version 1.0.0! 🎉

**Comment by jean997** [comment]
That's great. I see that function names have changed names. Are there other changes I should know about?

**Comment by willwerscheid** [comment]
Function names and argument names. It should simply be a matter of updating those.

**Comment by jean997** [comment]
Ok I think we are up to date!

**Comment by pcarbo** [comment]
Nice! Feel free to close this issue.
